name: fbt_hht
description: "Warehouse Management System - Flutter version"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.8.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^13.0.0
  
  # Network
  dio: ^5.4.0
  retrofit: ^4.9.1
  json_annotation: ^4.8.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Utils
  intl: ^0.20.2
  crypto: ^3.0.3
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2
  
  # Scanner
  mobile_scanner: ^3.5.0
  
  # Camera & Image
  image_picker: ^1.0.0
  
  # Sound
  audioplayers: ^5.2.1
  
  # Device Info
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  barcode_scan2: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
